### ISSUE TITLE
java.lang.NoSuchMethodError: no non-static method with name='setNonPersonalizedAd' 

### ISSUE THREAD

**Issue by marc1992** [Unity-Technologies/HuaweiServiceSample#10]
I am trying to use the plugin to integrate Huawei ads but I have an issue when I try to set non personalized ads. Unfortunatelly I can't use the plugin without that due to europe restrictions.

My code:

            RequestOptions reqOptions =  HwAds.getRequestOptions()
                .toBuilder()
                .setNonPersonalizedAd(NonPersonalizedAd.ALLOW_ALL)
                .build();
            HwAds.setRequestOptions(reqOptions);

Error:
 AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='setNonPersonalizedAd' signature='(I)Ljava/lang/Object;' in class Ljava.lang.Object;
java.lang.NoSuchMethodError: no non-static method with name='setNonPersonalizedAd' signature='(I)Ljava/lang/Object;' in class Ljava.lang.Object;
	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:229)
	at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
	at com.unity3d.player.ReflectionHelper.a(Unknown Source:0)
	at com.unity3d.player.ReflectionHelper$1.invoke(Unknown Source:83)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy12.onSuccess(Unknown Source)
	at com.huawei.hms.ads.consent.inter.Consent$1$4.run(Unknown Source:38)
	at com.huawei.hms.ads.consent.y.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
  at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x0003c] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1397 
  at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00001] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJNI.bindings.cs:61 
  at UnityEngine._AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x00001] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1354 
  at UnityEngine.AndroidJNIHelper.GetMethodID[ReturnType] (System.IntPtr jclass, System.String methodName, System.Object[] args, System.Boolean isStatic) [0x00001] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJNI.bindings.cs:166 
  at UnityEngine.AndroidJavaObject._Call[ReturnType] (System.String methodName, System.Object[] args) [0x00011] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:423 
  at UnityEngine.AndroidJavaObject.Call[ReturnType] (System.String methodName, System.Object[] args) [0x00001] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:307 
  at HuaweiService.HmsClass`1[T].Call[K] (System.String name, System.Object[] args) [0x00023] in C:\Users\markb\Downloads\HuaweiServiceSample-master (1)\HuaweiServiceSample-master\Assets\HuaweiService\fundation\HmsClass.cs:48 
  at HuaweiService.ads.RequestOptions+Builder.setNonPersonalizedAd (System.Int32 arg0) [0x00001] in C:\Users\markb\Downloads\HuaweiServiceSample-master (1)\HuaweiServiceSample-master\Assets\HuaweiService\ads\RequestOptions.cs:53 
  at HuaweiServiceDemo.MConsentUpdateListener.onSuccess (HuaweiService.ads.ConsentStatus arg0, System.Boolean isNeedConsent, HuaweiService.List arg2) [0x0009a] in C:\Users\markb\Downloads\HuaweiServiceSample-master (1)\HuaweiServiceSample-master\Assets\HuaweiServiceDemo\Scripts\test\ads\AdsListener.cs:112 
  at HuaweiService.ads.ConsentUpdateListener.onSuccess (UnityEngine.AndroidJavaObject arg0, System.Boolean arg1, UnityEngine.AndroidJavaObject arg2) [0x00001] in C:\Users\markb\Downloads\HuaweiServiceSample-master (1)\HuaweiServiceSample-master\Assets\HuaweiService\ads\ConsentUpdateListener.cs:19 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <2b3a3162be434770b7a4fac8b896e90c>:0 
Rethrow as TargetInvocationException: HuaweiServiceDemo.MConsentUpdateListener.onSuccess(UnityEngine.AndroidJavaObject,System.Boolean,UnityEngine.AndroidJavaObject)
  at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x000cc] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:113 
  at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, UnityEngine.AndroidJavaObject[] javaArgs) [0x00052] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:134 
  at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) [0x0005b] in /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:964 

(Filename: /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs Line: 1397)

**Comment by SiyaoHuang** [comment]
This is a bug. In Huawei SDK value `NonPersonalizedAd.ALLOW_ALL` is `int`, while the function needs an `Integer`. I add Integer class and a demo for setNonPersonalizedAd. 
[Link to demo code](https://github.com/Unity-Technologies/HMSSDKSample/blob/1d480bd21013c1548a283be53eaf14292b9c33cd/Assets%2FHuaweiServiceDemo%2FScripts%2Ftest%2Fads%2FAdsTest.cs#L57-L66)

You can pull master to check it. 

By the way, Would you like to leave review in assets store? It helps a lot for improving this project.

**Comment by marc1992** [comment]
Thanks for your fast answer and fix. 
I have added a review in the store 👍
