### ISSUE TITLE
Service Demo Not working

### ISSUE THREAD

**Issue by harunuysali07** [Unity-Technologies/HuaweiServiceSample#3]
Gives this error on Init button in ServiceDemo scene.
I'm using Huawei P40 Lite

```
2020/09/18 13:51:50.034 13362 18588 Error Unity AndroidJavaException: java.lang.reflect.UndeclaredThrowableException
2020/09/18 13:51:50.034 13362 18588 Error Unity java.lang.reflect.UndeclaredThrowableException
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at $Proxy12.init(Unknown Source)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at com.unity.udp.extension.sdk.games.UdpGames.init(UdpGames.java:80)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:106)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at android.os.Looper.loop(Looper.java:219)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2020/09/18 13:51:50.034 13362 18588 Error Unity Caused by: java.lang.reflect.InvocationTargetException
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at java.lang.reflect.Method.invoke(Native Method)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at com.unity.udp.extension.sdk.games.UdpGames$1.invoke(UdpGames.java:40)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	... 8 more
2020/09/18 13:51:50.034 13362 18588 Error Unity Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/huawei/hms/jos/JosApps;
2020/09/18 13:51:50.034 13362 18588 Error Unity 	at com.unity.udp.huawei.extension.games.HuaweiUdpGames.init(HuaweiUdpGames.java:50)
2020/09/18 13:51:50.034 13362 18588 Error Unity 	... 11 more
2020/09/18 13:51:50.034 13362 18588 Error Unity Caused 
```

I think it's caused by Unity HMS SDK

**Comment by CoffeyMiao** [comment]
Have you configured HMS game dependencies in gradle?
   
```
     dependencies {
         ...
         implementation 'com.huawei.agconnect:agconnect-core:1.2.0.300'
         implementation 'com.huawei.hms:base:4.0.1.300'
         implementation 'com.huawei.hms:hwid:4.0.1.300'
         implementation 'com.huawei.hms:game:4.0.1.300'
         ...
         }
```
