### ISSUE TITLE
按照官方的教程做，安装到手机上测试后闪退

### ISSUE THREAD

**Issue by GrimPan** [Unity-Technologies/HuaweiServiceSample#31]
02-28 01:05:07.784: E/AndroidRuntime(24036): Process: com.pan.myspacestationlive, PID: 24036
02-28 01:05:07.784: E/AndroidRuntime(24036): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.pan.myspacestationlive/com.hms.hms_analytic_activity.HmsAnalyticActivity}: java.lang.ClassNotFoundException: Didn't find class "com.hms.hms_analytic_activity.HmsAnalyticActivity" on path: DexPathList[[zip file "/data/app/com.pan.myspacestationlive-zkvdQXGRRM1OFKIel8OLAQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.pan.myspacestationlive-zkvdQXGRRM1OFKIel8OLAQ==/lib/arm, /data/app/com.pan.myspacestationlive-zkvdQXGRRM1OFKIel8OLAQ==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3978)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.os.Handler.dispatchMessage(Handler.java:110)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.os.Looper.loop(Looper.java:219)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at java.lang.reflect.Method.invoke(Native Method)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
02-28 01:05:07.784: E/AndroidRuntime(24036): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.hms.hms_analytic_activity.HmsAnalyticActivity" on path: DexPathList[[zip file "/data/app/com.pan.myspacestationlive-zkvdQXGRRM1OFKIel8OLAQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.pan.myspacestationlive-zkvdQXGRRM1OFKIel8OLAQ==/lib/arm, /data/app/com.pan.myspacestationlive-zkvdQXGRRM1OFKIel8OLAQ==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1264)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3963)
02-28 01:05:07.784: E/AndroidRuntime(24036): 	... 11 more
02-28 01:05:07.784: E/GameParse(2644): parseGameSdkInfo: Failed to get appData for pkgName = com.pan.myspacestationlive
02-28 01:05:07.785: E/AwareLog(2702): KeyThreadRecognize: can not find max eas level for: com.pan.myspacestationlive
02-28 01:05:07.788: E/AwareLog(2702): AwareGameFreq: gameFreqGov is invalid.
02-28 01:05:07.809: E/HwGameAssistant-11.4.2.300-GamePerfConfigure(23414): getConfigFileVersion statusCode-3
02-28 01:05:07.812: E/HsmCoreServiceImpl(2644): onTransact in code is: 102
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is JAD
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is NOP
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is NOH
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is OCE
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is BRQ
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is ANG
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is ELS
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is ANA
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is TAH
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is LIO
02-28 01:05:07.813: E/Hicom_AbmConfigParser(2644): getAbmSwitchStatus, appPackageName in map is TAS
02-28 01:05:07.813: E/Hicom_MpAptDecisionSystem(2644): remove bind rules with uid = 11064have no policy
02-28 01:05:07.813: E/Hicom_MpAptDecisionSystem(2644): handleAppDied. multipathPolicy
02-28 01:05:07.817: E/GameParse(2644): parseGameSdkInfo: Failed to get appData for pkgName = com.pan.myspacestationlive
02-28 01:05:07.818: E/HwGameAssistant-11.4.2.300-GamePerfDataReporter(23414): handleGameBackground meet JSONException
02-28 01:05:07.831: E/DollieAdapterService(2644): notifyActivityState pkg:com.huawei.android.launcher/com.huawei.android.launcher.unihome.UniHomeLauncher state:2 fg:true mUid:10080
02-28 01:05:07.832: E/Booster_MatterAppRecommend(2644): [isMatterPackage]invalid mMatterPackagesConfig
02-28 01:05:07.867: E/WindowManager(1611): icon is null!!
02-28 01:05:07.873: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:07.890: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:07.895: E/WindowManager(1611): win=Window{8509b9 u0 HwFullScreenWindow} destroySurfaces: appStopped=true win.mWindowRemovalAllowed=false win.mRemoveOnExit=false
02-28 01:05:07.907: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:07.923: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:07.940: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:07.957: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:07.974: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:07.990: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.007: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.024: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.041: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.058: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.074: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.091: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.108: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.125: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.133: E/WindowManager(1611): win=Window{84c451 u0 Splash Screen com.pan.myspacestationlive EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
02-28 01:05:08.142: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.158: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.175: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.192: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.209: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.225: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.242: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.259: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.276: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.287: E/AwareLog(1072): KeyThreadRecognize:send keyThreadMsg error
02-28 01:05:08.287: E/AwareLog(1072): KeyThreadRecognize:Report HighLoadCpucluster to apk fail
02-28 01:05:08.292: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.309: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.326: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.343: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.360: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.376: E/hisi_effect(755): getSupported:278: Unsupported display effect feature!!
02-28 01:05:08.575: E/AwareLog(1072): KeyThreadRecognize:send keyThreadMsg error
02-28 01:05:08.575: E/AwareLog(1072): KeyThreadRecognize:Report HighLoadCpucluster to apk fail
02-28 01:05:08.727: E/Thermal-daemon:hw_thermal(1059): [shell_back] tempNew :23  tempOld :22
02-28 01:05:08.727: E/Thermal-daemon:hw_thermal(1059): Report temperature: [shell_back] temp :23  reportThreshold:1
02-28 01:05:08.727: E/Thermal-daemon:hw_thermal(1059): [shell_frame] tempNew :25  tempOld :24
02-28 01:05:08.727: E/Thermal-daemon:hw_thermal(1059): Report temperature: [shell_frame] temp :25  reportThreshold:1
02-28 01:05:08.728: E/Thermal-daemon:hw_thermal(1059): [ap] tempNew :28  tempOld :29
02-28 01:05:08.729: E/Thermal-daemon:hw_thermal(1059): Report temperature: [ap] temp :28  reportThreshold:1
02-28 01:05:08.863: E/AwareLog(1072): KeyThreadRecognize:send keyThreadMsg error
02-28 01:05:08.863: E/AwareLog(1072): KeyThreadRecognize:Report HighLoadCpucluster to apk fail
02-28 01:05:09.151: E/AwareLog(1072): KeyThreadRecognize:send keyThreadMsg error
02-28 01:05:09.151: E/AwareLog(1072): KeyThreadRecognize:Report HighLoadCpucluster to apk fail
02-28 01:05:09.439: E/AwareLog(1072): KeyThreadRecognize:send keyThreadMsg error
02-28 01:05:09.439: E/AwareLog(1072): KeyThreadRecognize:Report HighLoadCpucluster to apk fail

**Comment by SiyaoHuang** [comment]
按着教程创建了个空的吗？看报错`java.lang.ClassNotFoundException: Didn't find class "com.hms.hms_analytic_activity.HmsAnalyticActivity" on path:`，
使用了修改了manifest，但是没有加HmsAnalyticActivity.java， 还是加了混淆没有exclude HmsAnalyticActivity，导致找不到？
