### ISSUE TITLE
How to solve it ? help me.....

### ISSUE THREAD

**Issue by xzjGitHub** [Unity-Technologies/HuaweiServiceSample#7]
Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.unity.udp.extension.sdk.games.UdpGames
    java.lang.ClassNotFoundException: com.unity.udp.extension.sdk.games.UdpGames
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:88)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: com.unity.udp.extension.sdk.games.UdpGames
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method) 
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0) 
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:88) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:219) 
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20) 
      at UnityEngine.AndroidJNISafe.CheckException () [0x00091] in <549ed8055ed14737ac3b841d26182fec>:0 
      at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) [0x00011] in <549ed8055ed14737a

**Comment by CoffeyMiao** [comment]
Sorry for the late reply, this error is due to missing steps in the integration, please refer to the integration guide in the [document](https://docs.unity.cn/cn/Packages-cn/com.unity.huaweiservice@1.3/manual/gameservices.html).
